FROM python:3.10

WORKDIR /code


COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN useradd -m -u 1000 user
RUN chown user /code
USER user
COPY --chown=user . .


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]